# cortex-cli-completion-version: 1.0.66+185850.47d3f3ed24e7
# Cortex CLI completions for fish shell
complete -c cortex -f

# Options
complete -c cortex -l workdir -s w -d "Working directory"
complete -c cortex -l connection -s c -d "Snowflake connection name"
complete -c cortex -l model -s m -d "Model override"
complete -c cortex -l mode -d "Agent mode: 'standard' or 'code'"
complete -c cortex -l plan -d "Enable plan mode"
complete -c cortex -l bypass -d "Enable bypass safeguards mode (auto-approve all tool calls)"
complete -c cortex -l dangerously-allow-all-tool-calls -d "Enable bypass safeguards mode (auto-approve all tool calls)"
complete -c cortex -l auto-accept-plans -d "Auto-accept plan mode requests and confirmations without prompting"
complete -c cortex -l profile -d "Apply a profile configuration (from ~/.snowflake/cortex/profiles/)"
complete -c cortex -l resume -s r -d "Open the resume menu on startup or immediately resume a session by session ID"
complete -c cortex -l continue -d "Resume the most recent session"
complete -c cortex -l session-name -d "Name for the new session (ignored when resuming)"
complete -c cortex -l session-id -d "Set the session ID for a new session (ignored when resuming)"
complete -c cortex -l fork-session -d "When resuming, fork to a new session instead of continuing the existing one"
complete -c cortex -l setting-sources -d "Comma-separated list of setting sources to load: user, project. Empty string disables all."
complete -c cortex -l output-format -d "Output format: 'stream-json' for JSON streaming output"
complete -c cortex -l input-format -d "Input format: 'stream-json' for JSON stdin input (use with --output-format stream-json)"
complete -c cortex -l print -s p -d "Print a series of chat response and exit (in headless, non-interactive mode)"
complete -c cortex -l config -d "Path to a custom settings.json configuration file (default: ~/.snowflake/cortex/settings.json)"
complete -c cortex -l config-file -d "Path to Snowflake connection config file (connections.toml or config.toml)"
complete -c cortex -l skills -d "Path to a custom skills.json configuration file (default: ~/.snowflake/cortex/skills.json)"
complete -c cortex -l mcp -d "Enable MCP servers (use --no-mcp to disable)"
complete -c cortex -l auto-update -d "Auto-update on launch (use --no-auto-update to disable)"
complete -c cortex -l worktree -d "Create a new worktree with the specified branch name and start session in it"
complete -c cortex -l plugin-dir -d "Plugin directory or GitHub repo (owner/repo, owner/repo#branch, or URL). Can be repeated."
complete -c cortex -l shell -d "Shell executor for commands: 'powershell', 'cmd', or 'bash' (default: auto-detect; on Windows defaults to powershell)"
complete -c cortex -l allowed-tools -d "Tools that execute without prompting for permission (e.g. \"Bash(git *)\" \"Read\" \"Edit\")"
complete -c cortex -l disallowed-tools -d "Tools that are removed from the model's context and cannot be used (e.g. \"Bash(rm *)\" \"Task(Explore)\")"
complete -c cortex -l version -s V -d "Show version"
complete -c cortex -l snowflake-sandbox -d "Enable Snowflake server-side sandbox for coding agent (requires Snowhouse connection or dev mode)"
complete -c cortex -l include-partial-messages -d "Include partial message events for token-level streaming"
complete -c cortex -l max-turns -d "Maximum number of agentic turns per conversation round"
complete -c cortex -l effort -d "Thinking effort level: minimal, low, medium, high, or max"
complete -c cortex -l agent -d "Use a custom agent definition by name (from .cortex/agents/ or ~/.snowflake/cortex/agents/)"
complete -c cortex -l index -d "Build tgrep semantic search index on startup"
complete -c cortex -l mcp-config -d "MCP server configuration as a JSON string (e.g. '{\"mcpServers\": {\"server-name\": {\"type\": \"stdio\", \"command\": \"cmd\"}}}')"

# Commands
complete -c cortex -n "__fish_use_subcommand" -a "mcp" -d "Manage MCP servers"
complete -c cortex -n "__fish_use_subcommand" -a "acp" -d "Agent Client Protocol (ACP) commands"
complete -c cortex -n "__fish_use_subcommand" -a "profile" -d "Manage profiles"
complete -c cortex -n "__fish_use_subcommand" -a "skill" -d "Manage skill directories"
complete -c cortex -n "__fish_use_subcommand" -a "ctx" -d "Long-term AI memory and task management"
complete -c cortex -n "__fish_use_subcommand" -a "resume" -d "Resume a previous session"
complete -c cortex -n "__fish_use_subcommand" -a "update" -d "Update to latest version"
complete -c cortex -n "__fish_use_subcommand" -a "versions" -d "List locally installed versions"
complete -c cortex -n "__fish_use_subcommand" -a "worktree" -d "Manage git worktrees"
complete -c cortex -n "__fish_use_subcommand" -a "completion" -d "Shell completion scripts"
complete -c cortex -n "__fish_use_subcommand" -a "create-ui-launcher" -d "Build and install the macOS desktop web UI launcher"
complete -c cortex -n "__fish_use_subcommand" -a "connections" -d "Manage Snowflake connections"
complete -c cortex -n "__fish_use_subcommand" -a "search" -d "Search Snowflake objects or docs"
complete -c cortex -n "__fish_use_subcommand" -a "reflect" -d "Validate semantic model"
complete -c cortex -n "__fish_use_subcommand" -a "artifact" -d "Artifact operations"
complete -c cortex -n "__fish_use_subcommand" -a "analyst" -d "Cortex Analyst operations"
complete -c cortex -n "__fish_use_subcommand" -a "env" -d "Environment detection"
complete -c cortex -n "__fish_use_subcommand" -a "agents" -d "Discover and explore Cortex Agents"
complete -c cortex -n "__fish_use_subcommand" -a "attach" -d "Attach to a background agent"
complete -c cortex -n "__fish_use_subcommand" -a "airflow" -d "Interact with Apache Airflow"
